CREATE TABLE TB_SHOPPING
(
 CODIGO_Shopping VARCHAR(3) PRIMARY KEY,
 NOME_Shopping VARCHAR (40) NOT NULL ,
 ENDERECO_Shopping VARCHAR (30) NOT NULL,
 BAIRRO_Shopping VARCHAR(40),
 CIDADE_Shopping VARCHAR (30),
 UF_Shopping VARCHAR(2)
 )

CREATE TABLE TB_Lojas
(
    CODIGO_Loja VARCHAR(3) PRIMARY KEY,
    NOME_Loja VARCHAR(30) NOT NULL,
    CODIGO_Shopping VARCHAR(3),
    CNPJ_Loja VARCHAR(17) UNIQUE,
    CONSTRAINT FK_CODIGO_Shopping FOREIGN KEY (CODIGO_Shopping) REFERENCES TB_SHOPPING (CODIGO_Shopping)
)

CREATE TABLE TB_Cargos
(
    CODIGO_Cargo VARCHAR(5) PRIMARY KEY,
    NOME_Cargo VARCHAR(5) NOT NULL,
    COMISSAO_Cargo FLOAT
)

CREATE TABLE TB_Funcionarios
(
    CODIGO_Func VARCHAR(3) PRIMARY KEY,
    NOME_Func  VARCHAR(40) NOT NULL,
    GENERO CHAR(1) CHECK(GENERO in ('F', 'M')),
    NASCIMENTO DATE,
    CPF VARCHAR(11) UNIQUE,
    COD_Cargo VARCHAR(5),
    COD_Loja VARCHAR(3),
    ADMISSAO date,
    constraint FK_cod_loja  Foreign KEY (COD_Loja)  references TB_Lojas (CODIGO_Loja)
)