Algoritmo "TabelaPotencia"

Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    i:=0
        Escreval("Número   Quadradro     Cubo ")
    enquanto i <=10 faca
         Escreval("__________________________")
         Escreval(i, "      |", i^2, "      |", i^3)
         i:= i +1
    fimenquanto

Fimalgoritmo